Restore XPF feed

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,6 +5,8 @@ on:
     branches: [ "main", "release/*" ]
     tags:
       - '*'
+  pull_request:
+      branches: [ "main" ]
   workflow_dispatch: # manual trigger for stable release
     inputs:
       nuget:
@@ -49,13 +51,10 @@ jobs:
   publish-nightly-release:
     runs-on: ubuntu-latest
     needs: build
-    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
+    if: (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref == 'refs/heads/main'
     steps:
 
-      - uses: actions/download-artifact@v4
-        with:
-            name: xpf
-            path: ./nupkgs
+      # Only publish nightly for Avalonia, not XPF 
       - uses: actions/download-artifact@v4
         with:
             name: avalonia
@@ -64,35 +63,26 @@ jobs:
       - name: Publish Nightly release
         run: dotnet nuget push ./nupkgs/**/*.nupkg --api-key ${{secrets.NIGHTLY_FEED_API_KEY}} --source https://nuget-feed-nightly.avaloniaui.net/v3/index.json
 
-      - name: Clean packages
-        if: always()
-        run: rm -rf ./nupkgs
-    
-#  need a feed with access to from "ubuntu-latest" runners
-#  publish-xpf-release:
-#    runs-on: ubuntu-latest
-#    needs: build
-#    if: github.event_name == 'workflow_dispatch'
-#    steps:
-#
-#    - name: Check branch validity
-#      if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
-#      run: |
-#          echo "Error: stable_release can only be run on 'release/*' branches."
-#          exit 1
-#
-#    - uses: actions/download-artifact@v4
-#      with:
-#        name: xpf
-#        path: ./nupkgs
-#
-#    - name: Publish XPF release
-#      if: ${{ inputs.nuget }}
-#      run: dotnet nuget push ./nupkgs/**/*.nupkg  --api-key ${{secrets.baget_api_key}} --source ${{ vars.BAGET_API_URL }}
-#
-#    - name: Clean packages
-#      if: always()
-#      run: rm -rf ./nupkgs
+  publish-xpf-release:
+    runs-on: ubuntu-latest
+    needs: build
+    if: github.event_name == 'workflow_dispatch'
+    steps:
+
+    - name: Check branch validity
+      if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
+      run: |
+          echo "Error: stable_release can only be run on 'release/*' branches."
+          exit 1
+
+    - uses: actions/download-artifact@v4
+      with:
+        name: xpf
+        path: ./nupkgs
+
+    - name: Publish XPF release
+      if: ${{ inputs.nuget }}
+      run: dotnet nuget push ./nupkgs/**/*.nupkg  --api-key ${{secrets.XPF_FEED_API_KEY}} --source https://xpf-nuget-feed.avaloniaui.net/push/v3/index.json
 
   publish-accelerate-release:
     runs-on: ubuntu-latest
@@ -115,6 +105,3 @@ jobs:
       if: ${{ inputs.nuget }}
       run: dotnet nuget push ./nupkgs/**/*.nupkg --api-key ${{secrets.NUGET_FEED_API_KEY}} --source https://api.nuget.org/v3/index.json
 
-    - name: Clean packages
-      if: always()
-      run: rm -rf ./nupkgs
